# Generated by Django 3.1.1 on 2020-09-13 07:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('specializtions', models.CharField(max_length=64)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_number', models.IntegerField()),
                ('estimated_time', models.DateTimeField()),
                ('status', models.CharField(max_length=16)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.patient')),
            ],
            options={
                'ordering': ['hospital', 'department', 'token_number'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.hospital'),
        ),
    ]
