# Generated by Django 3.1.1 on 2020-09-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specializtions',
            new_name='specializations',
        ),
    ]
